variables:
  DOCKER_DRIVER: overlay2

cache:
  paths:
    - BackEnd/public/
    - BackEnd/node_modules/
    - FrontEnd/node_modules/

stages:
  - buildfrontend
  - dev_build

buildfrontend:
  only:
    - azure_login
  image: node:12
  stage: buildfrontend
  tags:
    - aws
    - m4-large
  script:
    - ls
    - cd ./FrontEnd 
    - npm install
    - ls
    - npm run build
    - mkdir -p ../BackEnd/public/web 
    - cp -rf ./dist/*.* ../BackEnd/public/web

dev_build:
  only:
    - azure_login
  image: docker
  stage: dev_build
  tags:
    - aws
    - m4-large
  script:
    - export COMMIT=$(date +"%Y%m%d%H%M")
    - echo ${COMMIT}
    - cd BackEnd
    - ls -a
    # - docker version
    - echo ${REPO_URL}/${REPO_PROJECT}:${COMMIT}
    - echo "$REPO_PASSWORD" | docker login -u "$REPO_USER" --password-stdin ${REPO_URL}
    - docker build --no-cache -t ${REPO_URL}/${REPO_PROJECT}:${COMMIT} .
    - docker tag ${REPO_URL}/${REPO_PROJECT}:${COMMIT} ${REPO_URL}/${REPO_PROJECT}:latest
    - docker push ${REPO_URL}/${REPO_PROJECT}:${COMMIT}
    - docker push ${REPO_URL}/${REPO_PROJECT}:latest



