variables:
  DOCKER_DRIVER: overlay2

cache:
  paths:
    - BackEnd/public/
    - BackEnd/node_modules/
    - FrontEnd/node_modules/

# .before_script_template: &build_test-integration
#   before_script:
#   # - sudo docker stop document_cicd
#   # - sudo docker container rm document_cicd
#   - sudo bash delDocker.sh
#   - sudo bash delNodeModule.sh
#   - sudo docker run --rm -v `pwd`/BackEnd:/myapp -t node:10.17.0-slim sh -x -c 'cd /myapp && npm install'
#   - sudo docker run --rm -v `pwd`/FrontEnd:/myapp -t node:10.17.0-slim sh -x -c 'cd /myapp && npm install'

stages:
  - buildfrontend
  - dev_build

buildfrontend:
  only:
    - azure_login
  image: node:12
  stage: buildfrontend
  tags:
    - aws
    - m4-large
  script:
    - ls
    - cd ./FrontEnd 
    - npm install
    - ls
    - npm run build
    - mkdir -p ../BackEnd/public/web 
    - cp -rf ./dist/*.* ../BackEnd/public/web

dev_build:
  only:
    - azure_login
  image: docker
  stage: dev_build
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  tags:
    - aws
    - m4-large
  script:
    - export COMMIT=$(date +"%Y%m%d%H%M")
    - echo ${COMMIT}
    - cd BackEnd
    - ls -a
    # - docker version
    - echo ${REPO_URL}/${REPO_PROJECT}/image:${COMMIT}
    - docker build -t ${REPO_URL}/${REPO_PROJECT} .
    - docker tag ${REPO_URL}/${REPO_PROJECT} ${REPO_URL}/${REPO_PROJECT}:latest
    - echo "$REPO_PASSWORD" | docker login -u "$REPO_USER" --password-stdin ${REPO_URL}
    - docker push ${REPO_URL}/${REPO_PROJECT}
    - docker push ${REPO_URL}/${REPO_PROJECT}:latest
