variables:
  DOCKER_DRIVER: overlay2

cache:
  paths:
    - BackEnd/public/
    - BackEnd/node_modules/
    - FrontEnd/node_modules/

stages:
  - buildfrontend
  - build
  - deploy

buildfrontend:
  only:
    - azure_login
  image: node:12
  stage: buildfrontend
  tags:
    - aws
    - m4-large
  script:
    - ls
    - cd ./FrontEnd
    - npm install
    - ls
    - npm run build
    - mkdir -p ../BackEnd/public/web
    - cp -rf ./dist/*.* ../BackEnd/public/web

dev_build:
  only:
    - azure_login
  image: docker
  stage: build
  services:
    - docker:dind
  tags:
    - aws
    - m4-large
  script:
    # - export COMMIT=$(date +"%Y%m%d%H%M")
    # - echo ${COMMIT}
    - echo ${CI_COMMIT_SHA:0:8}
    - cd BackEnd
    - ls -a
    # - docker version
    - echo ${REPO_URL}/${REPO_PROJECT}:${CI_COMMIT_SHA:0:8}
    - echo "$REPO_PASSWORD" | docker login -u "$REPO_USER" --password-stdin ${REPO_URL}
    - docker build --no-cache -t ${REPO_URL}/${REPO_PROJECT}:${CI_COMMIT_SHA:0:8} .
    - docker tag ${REPO_URL}/${REPO_PROJECT}:${CI_COMMIT_SHA:0:8} ${REPO_URL}/${REPO_PROJECT}:latest
    - docker push ${REPO_URL}/${REPO_PROJECT}:${CI_COMMIT_SHA:0:8}
    - docker push ${REPO_URL}/${REPO_PROJECT}:latest

dev_deploy:
  only:
    - azure_login
  image:
    name: chnbohwr/docker
    entrypoint: [""]
  stage: deploy
  tags:
    - aws
    - m4-large
  before_script:
     - mkdir -p /.kube/
     - cp $KUBECONFIG_DEV /.kube/config
     - kubectl get nodes
     - kubectl get pods -n ordersystem
  script:
    - echo ${CI_COMMIT_SHA:0:8}
    - kubectl create secret docker-registry ordersystem-docker-pull-secret
      --docker-server=$REPO_URL
      --docker-username=$REPO_USER
      --docker-password=$REPO_PASSWORD
      -n ordersystem
      -o yaml
      --dry-run | kubectl apply -f -
    - kubectl apply -f test_configmap.yml
    # - envsubst < test_configmap.yml | kubectl apply -f -
    - sed -i "s#__DOCKER_WEB_IMAGE__#${REPO_URL}/${REPO_PROJECT}:${CI_COMMIT_SHA:0:8}#" test_deploy.yml 
    - cat test_deploy.yml 
    - kubectl apply -f test_deploy.yml


