apiVersion: v1
kind: Service
metadata:
  labels:
    app: testsystem
  name: testsystem
  namespace: ordersystem
spec:
  type: LoadBalancer
  ports:
    - name: backend
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: testsystem
