apiVersion: v1
kind: Service
metadata:
  annotations:
    generated: by hyman
    kompose.cmd: kompose convert -c
    kompose.image-pull-secret: regcred
    kompose.service.expose: windwork.k8s.devpack.cc
    kompose.service.expose.tls-secret: windwork-k8s-devpack-cc-tls
    kompose.service.type: nodeport
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: windwork-web
  name: windwork-web
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    io.kompose.service: windwork-web
  type: NodePort
status:
  loadBalancer: {}
