apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: windwork-web
  name: windwork-web
  annotations:
    kubernetes.io/ingress.class: "nginx" # use the one that corresponds to your ingress controller.
    external-dns.alpha.kubernetes.io/target: "k8s.devpack.cc" # workaround https://github.com/kubernetes-incubator/external-dns/issues/377
spec:
  rules:
  - host: windwork.k8s.devpack.cc
    http:
      paths:
      - backend:
          serviceName: windwork-web
          servicePort: 3000
  tls:
  - hosts:
    - windwork.k8s.devpack.cc
    secretName: windwork-k8s-devpack-cc-tls
status:
  loadBalancer: {}
